type Tank = { x:number;y:number;vx:number;vy:number;angle:number;power:number;hp:number;cash:number;mass:number;isAI:boolean;alive:boolean;name:string;color:string;wins:number };
type Projectile={x:number;y:number;vx:number;vy:number;owner:number;radius:number;damage:number;alive:boolean};
const canvas=document.getElementById('game') as HTMLCanvasElement; const ctx=canvas.getContext('2d')!; const hud=document.getElementById('hud')!;
let w=innerWidth,h=innerHeight-48; canvas.width=w; canvas.height=h; addEventListener('resize',()=>{w=innerWidth;h=innerHeight-48;canvas.width=w;canvas.height=h;genTerrain();spawnTanks();});
const gravity=220; let wind=0; let turn=0; let phase:'title'|'battle'|'shop'|'over'='title'; let round=1;
const terrain:number[]=[]; const tanks:Tank[]=[]; let proj:Projectile|null=null; let msg='Press Enter to start Civic Audit';
function genTerrain(){terrain.length=0; let y=h*0.65; for(let x=0;x<w;x++){ y+= (Math.random()-0.5)*2; y=Math.max(h*0.35,Math.min(h*0.9,y)); terrain[x]=y; }}
function groundY(x:number){const ix=Math.max(0,Math.min(w-1,Math.floor(x)));return terrain[ix]??h*0.7;}
function spawnTanks(){tanks.length=0; const names=['Regular','Heir','Bureau Bot']; for(let i=0;i<3;i++){const x=(i+1)*w/4; tanks.push({x,y:0,vx:0,vy:0,angle:i===0?-0.8:-2.3,power:230,hp:100,cash:120,mass:30,isAI:i>0,alive:true,name:names[i],color:['#f4b942','#9ad1ff','#ff8db1'][i],wins:0});} settleAll(); turn=0; wind=(Math.random()-0.5)*80; }
function settleAll(){for(const t of tanks){t.y=groundY(t.x)-8; t.vx=0;t.vy=0;}}
function deform(cx:number,cy:number,r:number,add=false){for(let x=Math.max(0,cx-r)|0;x<Math.min(w,cx+r);x++){const dx=x-cx; const dy=Math.sqrt(Math.max(0,r*r-dx*dx)); if(add){terrain[x]=Math.min(terrain[x],cy-dy);} else {terrain[x]=Math.max(terrain[x],cy+dy);} }}
function fire(owner:number){const t=tanks[owner]; if(!t.alive||proj) return; const sp=t.power; proj={x:t.x+Math.cos(t.angle)*10,y:t.y+Math.sin(t.angle)*10,vx:Math.cos(t.angle)*sp,vy:Math.sin(t.angle)*sp,owner,radius:4,damage:32,alive:true};}
function nextTurn(){proj=null; for(const t of tanks) if(t.alive){t.y=groundY(t.x)-8;} const alive=tanks.filter(t=>t.alive); if(alive.length<=1){alive[0]&&(alive[0].wins++,msg=`${alive[0].name} secured narrative control.`); phase=alive[0]&&alive[0].wins>=3?'over':'shop'; return;} do{turn=(turn+1)%tanks.length;}while(!tanks[turn].alive); msg=`${tanks[turn].name} turn`; if(tanks[turn].isAI) setTimeout(aiAct,550);}
function aiAct(){if(phase!=='battle'||!tanks[turn].isAI) return; const me=tanks[turn]; const target=tanks.find((t,i)=>i!==turn&&t.alive)!; const dx=target.x-me.x; me.angle=Math.atan2(-120,dx); me.power=Math.min(320,Math.max(140,Math.abs(dx)*1.15)); fire(turn);}
addEventListener('keydown',(e)=>{const t=tanks[turn]; if(phase==='title'&&e.key==='Enter'){phase='battle';genTerrain();spawnTanks();msg='Civic Audit begins';return;} if(phase==='shop'&&e.key==='Enter'){phase='battle';round++;wind=(Math.random()-0.5)*80;msg='Redistribution complete';return;} if(phase==='over'&&e.key==='Enter'){for(const t of tanks)t.wins=0;phase='title';msg='Press Enter to start Civic Audit';return;} if(phase!=='battle'||t.isAI) return; if(e.key==='ArrowLeft') t.angle-=0.06; if(e.key==='ArrowRight') t.angle+=0.06; if(e.key==='ArrowUp') t.power=Math.min(360,t.power+8); if(e.key==='ArrowDown') t.power=Math.max(100,t.power-8); if(e.key===' ') fire(turn);});
function update(dt:number){if(phase==='battle'){for(const t of tanks){if(!t.alive) continue; t.vy+=gravity*dt; t.y+=t.vy*dt; const gy=groundY(t.x)-8; if(t.y>gy){const impact=Math.max(0,t.vy-80); t.hp-=impact*0.03; if(t.hp<=0) t.alive=false; t.y=gy; t.vy=0;}}
if(proj){proj.vy+=gravity*dt; proj.vx+=wind*dt*0.15; proj.x+=proj.vx*dt; proj.y+=proj.vy*dt; if(proj.x<0||proj.x>=w||proj.y>=h||proj.y>=groundY(proj.x)){deform(proj.x,proj.y,32,false); for(const [i,t] of tanks.entries()){if(!t.alive) continue; const d=Math.hypot(t.x-proj.x,t.y-proj.y); if(d<60){t.hp-=Math.max(0,proj.damage*(1-d/60)); if(t.hp<=0){t.alive=false; if(i!==proj.owner) tanks[proj.owner].cash+=60;}}} nextTurn();}}
if(!proj&&tanks[turn]?.isAI) aiAct(); }}
function draw(){ctx.clearRect(0,0,w,h); ctx.fillStyle='#2a3445'; ctx.fillRect(0,0,w,h); ctx.fillStyle='#4f5b2f'; ctx.beginPath(); ctx.moveTo(0,h); for(let x=0;x<w;x++)ctx.lineTo(x,terrain[x]??h); ctx.lineTo(w,h); ctx.closePath(); ctx.fill();
for(const [i,t] of tanks.entries()){if(!t.alive) continue; ctx.fillStyle=t.color; ctx.fillRect(t.x-10,t.y-8,20,10); ctx.strokeStyle='#111'; ctx.beginPath(); ctx.moveTo(t.x,t.y-3); ctx.lineTo(t.x+Math.cos(t.angle)*14,t.y-3+Math.sin(t.angle)*14); ctx.stroke(); if(i===turn&&phase==='battle'){ctx.strokeStyle='#fff';ctx.strokeRect(t.x-12,t.y-10,24,14);} }
if(proj){ctx.fillStyle='#ffd46b'; ctx.beginPath(); ctx.arc(proj.x,proj.y,proj.radius,0,Math.PI*2); ctx.fill();}
ctx.fillStyle='#f5e6b5'; ctx.fillText(`ScoreCard 34518: Uncle's Cheeseborger War`,12,18); ctx.fillText(msg,12,36);
hud.innerHTML=`<strong>Civic Audit ${round}</strong><span>Market Volatility: ${wind.toFixed(1)}</span><span>Turn: ${tanks[turn]?.name??'-'}</span>` + tanks.map(t=>`<span style="color:${t.color}">${t.name} Dignity:${Math.max(0,t.hp|0)} Uncle Money:${t.cash} Wins:${t.wins}</span>`).join('');
if(phase==='shop'){ctx.fillText('Redistribution Screen: press Enter for next round (+40 Uncle Money all)',12,54); for(const t of tanks){if(t.alive){t.cash+=40;t.hp=Math.min(100,t.hp+15);}} phase='battle';}
if(phase==='over'){ctx.fillText('Future Secured, Temporarily. Press Enter to restart.',12,54);} if(phase==='title'){ctx.fillText('Press Enter to begin',12,54);} }
let last=performance.now(); function loop(now:number){const dt=Math.min(0.033,(now-last)/1000);last=now; update(dt); draw(); requestAnimationFrame(loop);} genTerrain(); requestAnimationFrame(loop);
